version: '3.7'
services:
  mongo-db:
    image: mongo
    ports:
    - '27017:27017'
  server:
    build: express-server
    image: express-server
    ports:
    - '3000:3000'
    links:
      - mongo-db
  client:
    build: angular-app
    image: angular-app
    ports:
    - '80:80'
